### PR TITLE
Add #pragma once to all header files

### PR DESCRIPTION
**Pull request by MaxMansfield**
This commit addresses ISSUE #244 of the team-phoenix/phoenix repo
by adding the `#pragma once` directive to all header files

Changes:
    1. Added `#pragma once` just before the `#ifndef`
       preprocessor directive to all header files.

### CODE REVIEW

**Comment by athairus** [comment]
Hi there! We've been slowly making this change whenever we get around to touching a header file, but thanks for finishing the job!

As it stands your PR can't be merged as the `#ifdef FOO_H` traps are still there. Could you remove these too?

**Comment by MaxMansfield** [comment]
Sorry for the delay. I've got finals right now.

I couldn't find an `#ifdef FOO_H` trap. In fact I couldn't find an `#ifdef` that didn't seem necessary. 

Do you mean an `#ifndef FOO_H` trap? 

Sorry for the questions, I'm just trying to make sure I know what you mean before I go remove some code.

**Comment by athairus** [comment]
Yes, things like this:

```
#ifndef BACKENDCOMMON_H
#define BACKENDCOMMON_H
```

and at the end of each file:

```
#endif
```

**Comment by MaxMansfield** [comment]
I feel like it's best to have both or just not use `#pragma once` since it can fail if the file system contains links to the same file that the compiler cannot follow.

For example, NTFS supports hard links, but you can't detect that files are linked if you access the file system across a network.

[Read more on the wiki](https://en.wikipedia.org/wiki/Pragma_once#Caveats)

Of course, if you still want me to I will, it's no problem but I'm just throwing in my opinion...which is mostly based on hearsay; I've never actually had `#pragma once` fail myself.

Thoughts?

**Comment by athairus** [comment]
We don't intend to use symlinks with our header files. We like to keep things simple!

**Comment by MaxMansfield** [comment]
Sweet, I'll get on it.

**Comment by MaxMansfield** [comment]
alright, it should be ready now.

**Comment by athairus** [comment]
Looks good.

**Pull request merged**
